# tests.test_topological_sort_linked_list(topological_sort)
# tests.test_topological_sort_branching(topological_sort)
# tests.test_topological_sort_rejoining(topological_sort)
# tests.test_topological_sort_cyclic(topological_sort)